let Vuln = ExposureGraphNodes
| where (set_has_element(Categories, "device") and isnotnull(NodeProperties.rawData.highRiskVulnerabilityInsights)) or  ((set_has_element(Categories, "identity")  and NodeProperties.rawData.adminCount == "1"));
ExposureGraphEdges
| make-graph SourceNodeId --> TargetNodeId with Vuln on NodeId
| graph-match (SourceNode)-[edges]->(TargetNode)
//| where edges.EdgeLabel in ("has credentials of","Member Of" ,"Has role on","can authenticate to") and TargetNode.NodeLabel == "microsoft.compute/virtualmachines" and SourceNode.NodeLabel == "user"
project edges.EdgeLabel, edges.SourceNodeName, edges.TargetNodeName, SourceNode.NodeLabel , SourceNode.NodeName, SourceNode.NodeProperties
